// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import "dotenv/config";
import { defineConfig } from "prisma/config";

function defaultSqliteUrl(): string {
  const root = process.env.INIT_CWD ?? process.cwd();
  const resolved = path.resolve(root, "dev.db");
  const normalized = resolved.replace(/\\/g, "/");
  return `file:${normalized}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? defaultSqliteUrl(),
  },
});
